# Site settings
title: André Reis
description: >
  I love to help teams build awesome web applications. Enthusiast about distributed systems, UX, books, running and cooking.

# baseurl: "website" # the subpath of your site, e.g. /blog/
url: "https://reisandre.com" # the base hostname & protocol for your site

author:
  fullname: André Reis
  github: andre-reis
  linkedin: andr3reis
  email: message.reis+ws@gmail.com
  instagram: andr3reis
  deviantart: evilfriend
  twitter: andr3reis
  image: /assets/img/bw.png

# Syntax highlighting
highlightstyle: 'rainbow'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]


# Build settings
highlighter: null
markdown: kramdown

plugins:
  - jekyll-seo-tag

twitter:
  username: andr3reis
  card: summary_large_image
social:
  name: André Reis
  links:
    - https://twitter.com/andr3reis
    - https://www.linkedin.com/in/andr3reis
    - https://github.com/andre-reis

# make dates: 2019-09-17 18:51:12
# timezone: Europe/Amsterdam